apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-deployment
spec:
  selector:
    matchLabels:
      app: department
  template:
    metadata:
      labels:
        app: department
    spec:
      containers:
      - name: department
        image: piomin/department-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: department-service
spec:
  type: ClusterIP
  selector:
    app: department
  ports:
  - port: 8080
    targetPort: 8080
