spring:
  application:
    name: department-service
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
management:
  endpoints.web.exposure.include: '*'
  endpoint:
    health:
      show-details: always