apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-deployment-v1
spec:
  selector:
    matchLabels:
      app: organization
      version: v1
  template:
    metadata:
      labels:
        app: organization
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: organization
        image: piomin/organization-service
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /etc/podinfo
            name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-deployment-v2
spec:
  selector:
    matchLabels:
      app: organization
      version: v2
  template:
    metadata:
      labels:
        app: organization
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: organization
          image: piomin/organization-service
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/podinfo
              name: podinfo
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  type: ClusterIP
  selector:
    app: organization
  ports:
  - port: 8080
    targetPort: 8080
