apiVersion: apps/v1
kind: Deployment
metadata:
  name: organization-deployment
spec:
  selector:
    matchLabels:
      app: organization
  template:
    metadata:
      labels:
        app: organization
    spec:
      containers:
      - name: organization
        image: piomin/organization-service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: organization-service
spec:
  type: ClusterIP
  selector:
    app: organization
  ports:
  - port: 8080
    targetPort: 8080
